### ISSUE TITLE
Rare mutex deadlock during playback

### ISSUE THREAD

**Issue by 23doors** [wang-bin/mdk-sdk#275]
**Describe the bug**
Had a crash on iPhone that I cannot reproduce. Looks like some deadlock with mutexes. Possibly stack trace can clarify. 

**To Reproduce**
Cant really reproduce it consistently. 
But when it happened:
* it was a video with subtitles
* phone was rotated to landscape
* when orientation changed - code calls `setVideoSurfaceSize` - and looks like that is when it stopped being responsive at all

Not much to go on, but maybe you can find some potential deadlock or poisoned mutex with that.

**Expected behavior**

**Environment:**
 - OS: iOS

**Crash**

App was killed by OS cause it hanged completely. Stacktrace:

```
  libsystem_kernel    0x1ef744a78  __psynch_mutexwait
  libsystem_pthread   0x22788f2f0  _pthread_mutex_firstfit_lock_wait
  libsystem_pthread   0x22788ed04  _pthread_mutex_firstfit_lock_slow
  libc++.1            0x1af950760  std::__1::mutex::lock
  mdk                 0x105108b9c  mdk::abi::SubtitleImageProducer::Private::get (SubtitleImageProducer.cpp)
  mdk                 0x105108b9c  mdk::abi::SubtitleImageProducer::imagesAt (SubtitleImageProducer.cpp:908)
  mdk                 0x105108b9c  mdk::abi::MediaControlPush::getSubtitleImages (MediaControl.cpp:253)
  mdk                 0x105133454  mdk::abi::VideoPresenter::Private::ensureVideoRenderer::lambda::operator() (VideoPresenter.cpp:138)
  mdk                 0x105133454  std::__1::__invoke[abi:nn180100]<T> (invoke.h:344)
  mdk                 0x105133454  std::__1::__invoke_void_return_wrapper<T>::__call[abi:nn180100]<T> (invoke.h:419)
  mdk                 0x105133454  std::__1::__function::__alloc_func<T>::operator()[abi:nn180100] (function.h:169)
  mdk                 0x105133454  std::__1::__function::__func<T>::operator() (function.h:311)
  mdk                 0x10513d700  std::__1::function<T>::operator() (function.h)
  mdk                 0x10514ea58  mdk::abi::VideoRenderer::rendered (VideoOutput.cpp:978)
  mdk                 0x10513d700  std::__1::function<T>::operator() (function.h)
  mdk                 0x10513d390  mdk::abi::MetalVideo::afterRendering (MetalVideo.mm:752)
  mdk                 0x10513d390  mdk::abi::MetalVideo::render (MetalVideo.mm:666)
  mdk                 0x10513dc28  mdk::abi::MetalVideoRenderer::draw (MetalVideoRenderer.mm:101)
  mdk                 0x10514e33c  mdk::abi::VideoRenderer::redraw (VideoOutput.cpp:885)
  mdk                 0x10514d6b0  mdk::abi::VideoRenderer::draw (VideoOutput.cpp:808)
  mdk                 0x105116ee8  mdk::abi::Player::renderVideo (Player.cpp:387)
  fvp                 0x104fa77ec  Player.renderVideo (Player.swift:206)
  fvp                 0x104fa77ec  MTLPlayerView.draw (MTLPlayerView.swift:332)
  fvp                 0x104fa6db0  MTLPlayerView.draw (<compiler-generated>)
  fvp                 0x104fa6db0  MTLPlayerView.draw (<compiler-generated>:325)
  MetalKit            0x22f69d560  -[MTKView draw]
  QuartzCore          0x1a0e538bc  CA::Layer::layout_and_display_if_needed
  QuartzCore          0x1a0eaa910  CA::Context::commit_transaction
  QuartzCore          0x1a0e297c0  CA::Transaction::commit
  QuartzCore          0x1a0e6ca08  CA::Transaction::flush_as_runloop_observer
  UIKitCore           0x1a1bb3564  _UIApplicationFlushCATransaction
  UIKitCore           0x1a1bb0b60  __setupUpdateSequence_block_invoke_2
  UIKitCore           0x1a1bb09d4  _UIUpdateSequenceRun
  UIKitCore           0x1a1bb0624  schedulerStepScheduledMainSection
  UIKitCore           0x1a1bb1598  runloopSourceCallback
  CoreFoundation      0x19f380324  __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
  CoreFoundation      0x19f3802b8  __CFRunLoopDoSource0
  CoreFoundation      0x19f37ddbc  __CFRunLoopDoSources0
  CoreFoundation      0x19f37cfb8  __CFRunLoopRun
  CoreFoundation      0x19f37c82c  CFRunLoopRunSpecific
  GraphicsServices    0x1eb35c1c0  GSEventRunModal
  UIKitCore           0x1a1ee2eac  -[UIApplication _run]
  UIKitCore           0x1a1f915b0  UIApplicationMain
  UIKitCore           0x1a22cbfa4  block_destroy_helper.23
```

**Comment by wang-bin** [comment]
do you set any subtitle properties?

**Comment by 23doors** [comment]
Yes, on start I set subtitle.blur, subtitle.font, subtitle.font.size, subtitle.shadow etc.
But on orientation change, I dont change any of these. But I call setVideoSurfaceSize and set subtitles.scale

**Comment by wang-bin** [comment]
>   mdk                 0x105108b9c  mdk::abi::SubtitleImageProducer::Private::get (SubtitleImageProducer.cpp)

missing line number, it's weird. There are some changes in the latest build, but not sure if it can fix the issue

**Comment by 23doors** [comment]
So far it didnt happen again (yet). But there seems to be some regression with newest build. Subtitles are blinking 2-3 times (they disappear for a fraction of a second). This seems to stop after roughly 30s of playback. Didnt seem to happen with older build.

**Comment by wang-bin** [comment]
try the latest build

**Comment by 23doors** [comment]
Looks like blinking is fixed. Will close this one for now and reopen if that mutex deadlock happens again

**Comment by 23doors** [comment]
Looks like it still happens after all.

thread#1
```
 libsystem_kernel    0x1f316cb78  __psynch_mutexwait
  libsystem_pthread   0x22c75089c  _pthread_mutex_firstfit_lock_wait
  libsystem_pthread   0x22c75024c  _pthread_mutex_firstfit_lock_slow
  libc++.1            0x1b23a0760  std::__1::mutex::lock
  mdk                 0x105dcce98  std::__1::unique_lock<T>::unique_lock[abi:nn180100] (unique_lock.h:40)
  mdk                 0x105dcce98  std::__1::unique_lock<T>::unique_lock[abi:nn180100] (unique_lock.h:40)
  mdk                 0x105dcce98  mdk::abi::SubtitleImageProducer::Private::get (SubtitleImageProducer.cpp:650)
  mdk                 0x105dcce98  mdk::abi::SubtitleImageProducer::imagesAt (SubtitleImageProducer.cpp:908)
  mdk                 0x105dcce98  mdk::abi::MediaControlPush::getSubtitleImages (MediaControl.cpp:253)
  mdk                 0x105df7600  mdk::abi::VideoPresenter::Private::ensureVideoRenderer::lambda::operator() (VideoPresenter.cpp:138)
  mdk                 0x105df7600  std::__1::__invoke[abi:nn180100]<T> (invoke.h:344)
  mdk                 0x105df7600  std::__1::__invoke_void_return_wrapper<T>::__call[abi:nn180100]<T> (invoke.h:419)
  mdk                 0x105df7600  std::__1::__function::__alloc_func<T>::operator()[abi:nn180100] (function.h:169)
  mdk                 0x105df7600  std::__1::__function::__func<T>::operator() (function.h:311)
  mdk                 0x105e019bc  std::__1::function<T>::operator() (function.h)
  mdk                 0x105e130d8  mdk::abi::VideoRenderer::rendered (VideoOutput.cpp:994)
  mdk                 0x105e019bc  std::__1::function<T>::operator() (function.h)
  mdk                 0x105e0164c  mdk::abi::MetalVideo::afterRendering (MetalVideo.mm:752)
  mdk                 0x105e0164c  mdk::abi::MetalVideo::render (MetalVideo.mm:666)
  mdk                 0x105e01ee4  mdk::abi::MetalVideoRenderer::draw (MetalVideoRenderer.mm:103)
  mdk                 0x105e129bc  mdk::abi::VideoRenderer::redraw (VideoOutput.cpp:901)
  mdk                 0x105e11d2c  mdk::abi::VideoRenderer::draw (VideoOutput.cpp:824)
  mdk                 0x105ddb0a0  mdk::abi::Player::renderVideo (Player.cpp:387)
```

thread#2
```
  libsystem_kernel    0x1f316cb78  __psynch_mutexwait
  libsystem_pthread   0x22c75089c  _pthread_mutex_firstfit_lock_wait
  libsystem_pthread   0x22c75024c  _pthread_mutex_firstfit_lock_slow
  libc++.1            0x1b23a0760  std::__1::mutex::lock
  mdk                 0x105e22640  mdk::abi::SubtitleImageProducer::onPropertyChanged (SubtitleImageProducer.cpp)
  mdk                 0x105db0660  mdk::abi::Property::set (Property.cpp:26)
  mdk                 0x105dcd470  mdk::abi::Property::setProperty (Property.h:57)
  mdk                 0x105dcd470  mdk::abi::MediaControlPush::setComponentProperty (MediaControl.cpp:285)
  mdk                 0x105dd5f34  mdk::abi::MediaPlayer::setComponentProperty (MediaPlayer.cpp:591)
  mdk                 0x105ddafe0  mdk::abi::Player::onPropertyChanged (Player.cpp)
  mdk                 0x105db0660  mdk::abi::Property::set (Property.cpp:26)
  mdk                 0x105dac0dc  mdk::abi::Property::setProperty (Property.h:57)
```

**Comment by 23doors** [comment]
Also, subs render timing is still a bit off. Blinking is less noticeable but it still happens. And in older builds it didnt seem to happen at all.

**Comment by 23doors** [comment]
Seems that this hang isn't exactly that rare after all and can be reproduced quite easily.

1. open video with subs, wait for them to appear and pause so they still appear on screen.
2. start changing subtitle properties like subtitle.margin.y 10 -> 20 -> 10. 

After a few changes, it hangs.

**Comment by wang-bin** [comment]
thanks for your information. dead lock should be fixed in https://github.com/wang-bin/mdk-sdk/actions/runs/12766029598

which platform can I reproduce the blinking?

**Comment by 23doors** [comment]
Thanks! just tested and dead lock seems fixed!

Regarding blinking - I dont notice blinking on macos. But it happens on iOS (iPhone) and is usually only noticeable when starting playback and for a few subs afterwards. But for some reason, it usually stops happening after ~60s of playback.

**Comment by wang-bin** [comment]
try the latest build. I can reproduce the bug in my local build with more logs, I will fix it later, but now temporary revert some changes and the result should be the same as old versions.

**Comment by 23doors** [comment]
Thanks! Tested and seems it's fine now. Will report back if there are any issues.

**Comment by 23doors** [comment]
Tested a bit more. And blinking seems to still happen. But now its quite rare. Had like 5 occurrences in 10 minute playback.

**Comment by wang-bin** [comment]
fixed in https://github.com/wang-bin/mdk-sdk/actions/runs/12785443162

**Comment by 23doors** [comment]
thanks! looks like it doesnt happen now at all
